project:
  type: website

website:
  title: "Code Club"
  page-footer:
    left: "Created and maintained by the [Specialist Analytics Team](mailto:scwcsu.analytics.specialist@nhs.net)"
    center: "[SCW's GitHub Repository](https://github.com/NHS-South-Central-and-West)"
    right: "This page was built with [Quarto](https://quarto.org/)"


  sidebar:
    background: "#1C355E" # SCW Dark Blue
    logo: "images/code_club_pink_white.png"
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - href: schedule.qmd
        text: Schedule
      - section: "Resources"
        contents:
          - href: resources/ncf.qmd
            text: National Competency Framework
      - section: "Sessions"
        contents:
          - href: sessions/01-onboarding/index.qmd
            text: Python Onboarding
          - href: sessions/10-comparing-samples/index.qmd
            text: Regression - Comparing Samples
      - href: glossary.qmd
        text: Glossary

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true # table of contents
    code-copy: true
  revealjs:
    author: Specialist Analytics Team (SAT)
    menu: false
    controls: true
    section-divs: true
    preview-links: false
    link-external-newwindow: true
    embed-resources: true
    transition: fade
    background-transition: fade
    navigation-mode: linear
    email-obfuscation: javascript
    theme: slides-theme.scss
    progress: true
    multiplex: false
    scrollable: false
    hide-inactive-cursor: true
    highlight-style: printing
    pause: true
    fig-width: 6
    fig-height: 7
    fig-align: center
    output-location: column

editor: source

execute:
  freeze: auto
  echo: true
  warning: false

revealjs-plugins:
  - verticator

title-slide-attributes:
    data-background-image: "images/scw_logo.jpg"
    data-background-position: "right 5% bottom 5%"
    data-background-size: "22%"
    data-background-opacity: "1"

from: markdown+emoji
