project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - resources.qmd
    - schedule.qmd
    - 404.qmd
    - glossary.qmd

website:
  title: "Code Club"
  page-footer:
    left: "Created and maintained by the [Specialist Analytics Team](mailto:scwcsu.analytics.specialist@nhs.net)"
    right: "This page was built with [Quarto](https://quarto.org/)"


  sidebar:
    background: "#1C355E" # SCW Dark Blue
    logo: "images/code_club_pink_white.png"
    pinned: true
    align: center
    style: docked
    tools:
      - icon: github # not sure how to invert the colour on dark background
        href: https://github.com/NHS-South-Central-and-West
        text: "SCW's GitHub"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - href: schedule.qmd
        text: Schedule
      - section: "Resources"
        contents:
          - href: resources.qmd
          - text: Resources
      - href: glossary.qmd
        text: Glossary

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true # table of contents
    code-copy: true



