project:
  type: website

website:
  title: "Code Club"
  page-footer:
    left: "Created and maintained by the [Specialist Analytics Team](mailto:scwcsu.analytics.specialist@nhs.net)"
    center: "[SCW's GitHub Repository](https://github.com/NHS-South-Central-and-West)"
    right: "This page was built with [Quarto](https://quarto.org/)"


  sidebar:
    background: "#1C355E" # SCW Dark Blue
    logo: "images/code_club_pink_white.png"
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - href: schedule.qmd
        text: Schedule
      - section: "Resources"
        contents:
          - href: resources/ncf.qmd
            text: National Competency Framework
      - href: glossary.qmd
        text: Glossary

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true # table of contents
    code-copy: true

execute:
  freeze: auto

